# Generated by Django 2.0.6 on 2018-11-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('user_management', '权限管理'), ('irarea_management', '感兴趣区域'), ('current_situation', '区域现状'), ('resource_status', '资源分类统计'), ('history_event', '历史事件统计'), ('resource_check', '资源分类详查'), ('ibuild_management', '违建管理'), ('demolition_management', '拆迁管理'), ('recource_management', '影像管理'))},
        ),
        migrations.AddField(
            model_name='myuser',
            name='my_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='graphiclabel',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
